### ISSUE TITLE
Is CV() available?

### ISSUE THREAD

**Issue by Fredo-XVII** [mitchelloharawild/tidy-forecasting-principles#2]
Hello,

I wanted to do a CV() to compare 4 to 5 different models as discussed in the RStudio 2020 training, but I can't find the function anywhere, including this repo except in the documentation for accuracy().

I believe this is the function that I am looking for: `CV(tsbl, mdl, h, window_type, ...)`, but there is no documentation on how to use it.  In addition, it is not in any of the 3 packages of fpp3, those being fable, fabletools, and feasts.

Am i missing something?

Thanks!

**Comment by mitchelloharawild** [comment]
Instructions for performing time series cross validation can be found here: https://otexts.com/fpp3/tscv.html

**Comment by Fredo-XVII** [comment]
Great, thank you!
